version: '2.1'

services:
  azurecontainerinstances.jobgenerator:
    ports:
      - "80"

  azurecontainerinstances.logging:
    ports:
      - "80"
networks:
  default:
    external:
      name: nat
