version: '2.1'
services:
  azurecontainerinstances.jobgenerator:
    image: "azurecontainerinstances.jobgenerator"     
    build:
      context: .\AzureContainerInstances.JobGenerator
      dockerfile: Dockerfile
    environment:
      - "Microsoft.ServiceBus.ConnectionString="

  azurecontainerinstances.jobprocessing:
    image: "azurecontainerinstances.jobprocessing"
    build:
      context: .\AzureContainerInstances.JobProcessing
      dockerfile: Dockerfile
    environment:
      - "Microsoft.ServiceBus.ConnectionString="

  azurecontainerinstances.logging:
    image: "azurecontainerinstances.logging"    
    build:
      context: .\AzureContainerInstances.Logging
      dockerfile: Dockerfiles
    environment:
      - "Microsoft.ServiceBus.ConnectionString="